{
 "title": "SGI节点GPU监控",
 "description": "SGI节点GPU监控",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gpu_node",
    "query": "label_values(nvidia_gpu_num_devices, node_name)"
   },
   {
    "name": "GPU",
    "query": "label_values(nvidia_gpu_memory_used_bytes{node_name=~\"$gpu_node\"}, uuid)"
   }
  ]
 },
 "panels": [
  {
   "title": "Avg Temperature",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg (nvidia_gpu_temperature_celsius{node_name=~\"$gpu_node\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "nvidia_gpu_temperature_celsius",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Power Usage",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "mwatt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (nvidia_gpu_power_usage_milliwatts)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Number Per Node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_num_devices{node_name=~\"$gpu_node\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{node_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum (nvidia_gpu_num_devices{node_name=~\"$gpu_node\"})",
     "legendFormat": "totall"
    }
   ]
  },
  {
   "title": "Totall GPU AVG Duty Cycle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_duty_cycle{node_name=~\"$gpu_node\", uuid=~\"$GPU\"}) /\nsum (nvidia_gpu_num_devices{node_name=~\"$gpu_node\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AVG GPU  Duty Cycle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Duty Cycle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_duty_cycle{node_name=~\"$gpu_node\", uuid=~\"$GPU\"}) by (uuid, node_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{uuid}}  {{node_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total GPU  AVG Memory Util",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_memory_used_bytes) / \nsum (nvidia_gpu_memory_total_bytes) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Toall-Nodes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum (nvidia_gpu_memory_used_bytes{node_name=~\"$gpu_node\", uuid=~\"$GPU\"}) /\nsum (nvidia_gpu_memory_total_bytes{node_name=~\"$gpu_node\", uuid=~\"$GPU\"}) * 100 ",
     "legendFormat": "[[gpu_node]]"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_memory_used_bytes{node_name=~\"$gpu_node\", uuid=~\"$GPU\"} / \nnvidia_gpu_memory_total_bytes{node_name=~\"$gpu_node\", uuid=~\"$GPU\"} * 100) by (uuid, node_name)",
     "legendFormat": "{{uuid}}  ({{node_name}})"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_temperature_celsius{node_name=~\"$gpu_node\", uuid=~\"$GPU\"}) by (uuid, node_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{uuid}}  ({{node_name}})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_power_usage_milliwatts{node_name=~\"$gpu_node\", uuid=~\"$GPU\"}) by (uuid,node_name)",
     "legendFormat": "{{uuid}}  {{node_name}}"
    }
   ]
  }
 ]
}