{
 "title": "GPU应用监控",
 "tags": [ "GPU" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gpu_node",
    "query": "label_values(nvidia_gpu_memory_used_bytes, node_name)"
   },
   {
    "name": "namespace_name",
    "query": "label_values(nvidia_gpu_memory_used_bytes{node_name=~\"$gpu_node\"}, namespace_name)"
   },
   {
    "name": "gpu_pod_name",
    "query": "label_values(nvidia_gpu_memory_used_bytes{node_name=~\"$gpu_node\", namespace_name=~\"$namespace_name\"}, pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum ( nvidia_gpu_memory_used_bytes{pod_name=~\"$gpu_pod_name\", container_name!=\"\", node_name=~\"$gpu_node\"} / \nnvidia_gpu_memory_total_bytes{pod_name=~\"$gpu_pod_name\", container_name!=\"\", node_name=~\"$gpu_node\"} * 100)\nby (pod_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_memory_used_bytes{pod_name=~\"$gpu_pod_name\", container_name!=\"\", node_name=~\"$gpu_node\"}) by (pod_name)",
     "legendFormat": "used: {{pod_name}} "
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_power_usage_milliwatts{pod_name=~\"$gpu_pod_name\", container_name!=\"\", node_name=~\"$gpu_node\"}) by (pod_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duty Cycle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (nvidia_gpu_duty_cycle{pod_name=~\"$gpu_pod_name\", container_name!=\"\", node_name=~\"$gpu_node\"}) by (pod_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg (nvidia_gpu_temperature_celsius{pod_name=~\"$gpu_pod_name\", container_name!=\"\", node_name=~\"$gpu_node\"}) by (pod_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pod_name}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}