{
 "title": "SGI  NODE MONITOR",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": "label_values(nvidia_gpu_num_devices, node_name)"
   },
   {
    "name": "uuid",
    "query": "label_values(nvidia_gpu_num_devices{node_name=~\"$node_name\"}, uuid)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU NUMBER PER NODE",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(nvidia_gpu_num_devices{node_name=~\"$node_name\"}) by (node_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TOTAL",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(nvidia_gpu_num_devices{node_name=~\"$node_name\", used=\"true\"}) by (node_name)"
    }
   ]
  },
  {
   "title": "TOTAL GPU AVG DUTY CYCLE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_duty_cycle{node_name=~\"$node_name\", uuid=~\"$uuid\"}) /\nsum (nvidia_gpu_num_devices{node_name=~\"$node_name\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TOTAL GPU AVG DUTY CYCLE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TOTAL MEMORY AND USED MEMORY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_total_bytes{node_name=~\"$node_name\", uuid=~\"$uuid\"}) by (node_name, uuid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(nvidia_gpu_memory_used_bytes{node_name=~\"$node_name\", uuid=~\"$uuid\"}) by (node_name, uuid)"
    }
   ]
  },
  {
   "title": "TOTAL GPU  AVG MEMORY UTIL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_memory_used_bytes) / \nsum (nvidia_gpu_memory_total_bytes) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TOTAL USAGE PERCENTAGE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum (nvidia_gpu_memory_used_bytes{node_name=~\"$node_name\", uuid=~\"$uuid\"}) /\nsum (nvidia_gpu_memory_total_bytes{node_name=~\"$node_name\", uuid=~\"$uuid\"}) * 100",
     "legendFormat": "PERCENTAGE OF SELECTED NODE AND GPU"
    }
   ]
  },
  {
   "title": "AVG GPU Duty Cycle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_duty_cycle{node_name=~\"$node_name\", uuid=~\"$uuid\"}) by (node_name)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum(nvidia_gpu_duty_cycle{node_name=~\"$node_name\", uuid=~\"$uuid\"}) by (node_name, uuid)"
    }
   ]
  },
  {
   "title": "POWER USAGE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_power_usage_milliwatts{node_name=~\"$node_name\", uuid=~\"$uuid\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TOTAL OF SELECTED NODE AND GPU",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum (nvidia_gpu_power_usage_milliwatts{node_name=~\"$node_name\", uuid=~\"$uuid\"}) by (node_name)"
    },
    {
     "expr": "sum (nvidia_gpu_power_usage_milliwatts{node_name=~\"$node_name\", uuid=~\"$uuid\"}) by (node_name, uuid)"
    }
   ]
  },
  {
   "title": "TEMPERATURE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(nvidia_gpu_temperature_celsius{node_name=~\"$node_name\", uuid=~\"$uuid\"}) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TOTAL OF SELECTED NODE AND GPU",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg(nvidia_gpu_temperature_celsius{node_name=~\"$node_name\", uuid=~\"$uuid\"}) by (node_name)"
    },
    {
     "expr": "avg(nvidia_gpu_temperature_celsius{node_name=~\"$node_name\", uuid=~\"$uuid\"}) by (node_name, uuid)"
    }
   ]
  }
 ]
}