{
 "title": "SGI App Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_name",
    "query": "label_values(nvidia_gpu_memory_used_bytes, node_name)"
   },
   {
    "name": "namespace_name",
    "query": "label_values(nvidia_gpu_memory_total_bytes{node_name=~\"$node_name\"},namespace_name)"
   },
   {
    "name": "project",
    "query": "label_values(nvidia_gpu_memory_total_bytes{node_name=~\"$node_name\",namespace_name=~\"$namespace_name\"}, project)"
   },
   {
    "name": "user",
    "query": "label_values(nvidia_gpu_memory_total_bytes{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\"}, user)"
   },
   {
    "name": "pod_name",
    "query": "label_values(nvidia_gpu_memory_used_bytes{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\",project=~\"$project\",user=~\"$user\"}, pod_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU USAGE PERCENTAGE",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_num_devices{used=\"true\"})/sum(nvidia_gpu_num_devices)*100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PROJECT GPU USAGE",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count(nvidia_gpu_duty_cycle{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) by (project)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU USAGE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(nvidia_gpu_duty_cycle{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TOTAL GPU USAGE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "count(nvidia_gpu_duty_cycle{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) by (pod_name)"
    },
    {
     "expr": "count(nvidia_gpu_duty_cycle{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) by (node_name, uuid)"
    }
   ]
  },
  {
   "title": "DURTY CYCLE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_duty_cycle) /\nsum (nvidia_gpu_num_devices)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AVERAGE DURTY BY SELECTED",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg (nvidia_gpu_duty_cycle{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) by (pod_name)"
    },
    {
     "expr": "sum (nvidia_gpu_duty_cycle{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) by (node_name, uuid)"
    },
    {
     "expr": "sum (nvidia_gpu_duty_cycle{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) /\nsum (nvidia_gpu_num_devices{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\"})"
    }
   ]
  },
  {
   "title": "TOTAL MEMORY",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_memory_total_bytes{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Total memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum (nvidia_gpu_memory_used_bytes{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"})",
     "legendFormat": "Used memory"
    },
    {
     "expr": "sum (nvidia_gpu_memory_used_bytes{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) by (node_name,uuid)"
    }
   ]
  },
  {
   "title": "MEMORY USAGE PERCENRTAGE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(sum(nvidia_gpu_memory_used_bytes{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"})/sum(nvidia_gpu_memory_total_bytes{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "MEMORY PERCENTAGE BY SELECED ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TEMPERATURE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (nvidia_gpu_temperature_celsius{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "AVERAGE GPU TEMPERATURE SELECTED ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "avg (nvidia_gpu_temperature_celsius{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) by (pod_name)"
    },
    {
     "expr": "\navg (nvidia_gpu_temperature_celsius{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) by (node_name, uuid)"
    }
   ]
  },
  {
   "title": "POWER USAGE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "sum (nvidia_gpu_power_usage_milliwatts{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "TOTAL POWER",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "sum (nvidia_gpu_power_usage_milliwatts{node_name=~\"$node_name\", namespace_name=~\"$namespace_name\", project=~\"$project\", user=~\"$user\", pod_name=~\"$pod_name\", used=\"true\"}) by (node_name,uuid)"
    }
   ]
  }
 ]
}