apiVersion: v1
kind: Service
metadata:
  labels:
    app: ceph-exporter
    k8s-app: ceph-exporter
  name: ceph-exporter
spec:
  clusterIP: None
  ports:
  - name: web
    port: 9128
    protocol: TCP
    targetPort: 9128
  selector:
    app: ceph-exporter
  type: ClusterIP
#---
#apiVersion: monitoring.coreos.com/v1alpha1
#kind: ServiceMonitor
#metadata:
#  labels:
#    app: ceph-exporter
#  name: ceph-exporter
#  namespace: monitoring
#spec:
#  endpoints:
#  - interval: 10s
#    port: web
#  namespaceSelector:
#    matchNames:
#    - monitoring
#  selector:
#    matchLabels:
#      app: ceph-exporter
