apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
  creationTimestamp: 2018-05-05T03:30:57Z
  generation: 15
  labels:
    k8s-app: grafana
    task: monitoring
  name: monitoring-grafana
  namespace: kube-system
  resourceVersion: "68567422"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/monitoring-grafana
  uid: b91da17d-5014-11e8-b497-90b8d0abcd2b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: grafana
      task: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: grafana
        task: monitoring
    spec:
      containers:
      - env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb.kube-system
        - name: GF_SERVER_HTTP_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /
        image: registry.gcloud.srcb.com/registry.cn-hangzhou.aliyuncs.com/acs/grafana:5.0.4-gpu-monitoring
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certificates
          readOnly: true
        - mountPath: /var
          name: grafana-storage
        - mountPath: /etc/grafana/
          name: grafana-etc-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        role: master
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /etc/ssl/certs
          type: ""
        name: ca-certificates
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana
      - configMap:
          defaultMode: 420
          items:
          - key: grafana.ini
            path: grafana.ini
          name: grafana-etc
        name: grafana-etc-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-05-05T03:30:57Z
    lastUpdateTime: 2018-05-05T03:30:57Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-05-05T03:30:57Z
    lastUpdateTime: 2019-04-12T03:39:11Z
    message: ReplicaSet "monitoring-grafana-7b677cb4f5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 15
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
